
DROP DATABASE IF EXISTS MiniTrelloBBDD;
CREATE DATABASE MiniTrelloBBDD;


CREATE TABLE users(
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	username VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(70) NOT NULL,
	email    VARCHAR(50) UNIQUE NOT NULL CHECK (email LIKE '%@%'),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE projects(
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	owner_id INTEGER NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_owner
		FOREIGN KEY (owner_id)
		REFERENCES users(id)
		ON DELETE CASCADE
	
);


CREATE TYPE task_status AS ENUM('todo', 'doing', 'done');

CREATE TABLE tasks(
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	project_id INTEGER NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	description VARCHAR(100),
	title VARCHAR(50) NOT NULL,
	status task_status NOT NULL DEFAULT 'todo',
	CONSTRAINT fk_project_id
		FOREIGN KEY (project_id)
		REFERENCES projects(id)
		ON DELETE CASCADE

);